/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 18 20:35:14 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ValidadorCPF_ESTest extends ValidadorCPF_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("9/Hn9sk6*44553o991");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("3Q/Hn9]sk6*44553 999");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("9Q2Hn9]6k6*4!553 999");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("9/ay9]sk6*44553999");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("9/Hn9]k6*44553|993");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("9/Hn9sk,6*446553o91");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("");
      assertFalse(boolean0);
  }
}
