/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 19 03:00:38 GMT 2026
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ValidadorCPF_ESTest extends ValidadorCPF_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("K1Y1:3889Wb62415=");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("515O:3889WY624s6=G");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("015O:3889Wb6245l4=G");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("015O:7889Wb624?5{=G");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("015O,:3889Wb6249l=G");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("K1Y1:3889Wb624K55=");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("8F~");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ValidadorCPF validadorCPF0 = new ValidadorCPF();
      boolean boolean0 = validadorCPF0.isValido("015O:3889Wb6245l=G");
      assertFalse(boolean0);
  }
}
